application: rwstoneback
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|pdf|eot|svg|ttf|woff|otf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf|eot|svg|ttf|woff|otf))
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
